// Fake but plausible data for the Nabodata web UI kit.
// Numbers are illustrative.

window.NABO_DATA = {
  norge: {
    name: 'Norge',
    population: 5550203,
    density: 17,
    medianIncome: 542000,
  },
  fylker: [
    { id: 'oslo',      name: 'Oslo',          density: 7, kommuner: ['Oslo'] },
    { id: 'viken',     name: 'Akershus',      density: 5, kommuner: ['Bærum', 'Asker', 'Lillestrøm', 'Nordre Follo'] },
    { id: 'innlandet', name: 'Innlandet',     density: 1, kommuner: ['Hamar', 'Lillehammer', 'Gjøvik', 'Elverum'] },
    { id: 'vestfold',  name: 'Vestfold',      density: 4, kommuner: ['Tønsberg', 'Sandefjord', 'Larvik'] },
    { id: 'agder',     name: 'Agder',         density: 2, kommuner: ['Kristiansand', 'Arendal', 'Grimstad'] },
    { id: 'rogaland',  name: 'Rogaland',      density: 3, kommuner: ['Stavanger', 'Sandnes', 'Haugesund'] },
    { id: 'vestland',  name: 'Vestland',      density: 3, kommuner: ['Bergen', 'Voss', 'Førde', 'Sogndal'] },
    { id: 'more',      name: 'Møre og Romsdal', density: 2, kommuner: ['Ålesund', 'Molde', 'Kristiansund'] },
    { id: 'trondelag', name: 'Trøndelag',     density: 2, kommuner: ['Trondheim', 'Steinkjer', 'Levanger'] },
    { id: 'nordland',  name: 'Nordland',      density: 1, kommuner: ['Bodø', 'Narvik', 'Mo i Rana'] },
    { id: 'troms',     name: 'Troms',         density: 1, kommuner: ['Tromsø', 'Harstad'] },
    { id: 'finnmark',  name: 'Finnmark',      density: 0, kommuner: ['Alta', 'Hammerfest', 'Kirkenes'] },
  ],
  // Selected detailed kommune profiles
  kommuner: {
    'Bergen': {
      fylke: 'Vestland',
      population: 285911, popTrend: 1.8,
      density: 624,
      medianIncome: 548200, incomeTrend: -0.3,
      ageBands: [11, 12, 14, 15, 12, 11, 9, 7, 4],
      origins: [
        { country: 'Polen',     n: 9412 },
        { country: 'Litauen',   n: 6640 },
        { country: 'Sverige',   n: 5075 },
        { country: 'Syria',     n: 3988 },
        { country: 'Tyskland',  n: 2901 },
        { country: 'Eritrea',   n: 2174 },
      ],
      income: [
        { band: '< 200k',   pct: 8 },
        { band: '200–400k', pct: 22 },
        { band: '400–600k', pct: 31 },
        { band: '600–800k', pct: 19 },
        { band: '800k–1M',  pct: 11 },
        { band: '> 1M',     pct: 9 },
      ],
      kostra: 78,
      housing: 'Tett',
      poi: { Skoler: 24, Helse: 11, Restauranter: 187, 'Religiøse bygg': 18, Friluft: 42 },
    },
    'Oslo': {
      fylke: 'Oslo',
      population: 717710, popTrend: 1.4,
      density: 1547,
      medianIncome: 612000, incomeTrend: 0.6,
      ageBands: [10, 11, 18, 19, 14, 11, 7, 6, 4],
      origins: [
        { country: 'Polen',     n: 14820 },
        { country: 'Sverige',   n: 9512 },
        { country: 'Pakistan',  n: 8804 },
        { country: 'Somalia',   n: 7322 },
        { country: 'Litauen',   n: 6190 },
        { country: 'Eritrea',   n: 5408 },
      ],
      income: [
        { band: '< 200k',   pct: 7 },
        { band: '200–400k', pct: 19 },
        { band: '400–600k', pct: 28 },
        { band: '600–800k', pct: 21 },
        { band: '800k–1M',  pct: 13 },
        { band: '> 1M',     pct: 12 },
      ],
      kostra: 82,
      housing: 'Svært tett',
      poi: { Skoler: 178, Helse: 92, Restauranter: 1240, 'Religiøse bygg': 110, Friluft: 211 },
    },
    'Tromsø': {
      fylke: 'Troms',
      population: 77544, popTrend: 0.9,
      density: 7,
      medianIncome: 558400, incomeTrend: 0.4,
      ageBands: [12, 13, 17, 16, 13, 11, 8, 6, 4],
      origins: [
        { country: 'Sverige',   n: 1124 },
        { country: 'Russland',  n: 902 },
        { country: 'Polen',     n: 740 },
        { country: 'Tyskland',  n: 612 },
        { country: 'Finland',   n: 508 },
        { country: 'Syria',     n: 412 },
      ],
      income: [
        { band: '< 200k',   pct: 9 },
        { band: '200–400k', pct: 24 },
        { band: '400–600k', pct: 32 },
        { band: '600–800k', pct: 18 },
        { band: '800k–1M',  pct: 10 },
        { band: '> 1M',     pct: 7 },
      ],
      kostra: 71,
      housing: 'Spredt',
      poi: { Skoler: 32, Helse: 18, Restauranter: 96, 'Religiøse bygg': 14, Friluft: 88 },
    },
  },
};
