export type {
  Fylke,
  KommuneSummary,
  Kommune,
  KommuneStats,
  PopulationStats,
  AgeDistribution,
  AgeBand,
  IncomeStats,
  EducationStats,
  MigrationStats,
  BusinessStats,
  HealthStats,
  ApiResponse,
  ApiError,
  Theme,
  Locale,
} from '@nabodata/types';
